# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
