# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200328_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machinery',
            new_name='Product',
        ),
    ]
