# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200407_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='artist',
            new_name='horsepower',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='manufacturer',
        ),
    ]
