# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-20 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200407_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
    ]
